version: '3'

services:
  redis:
    image: redis:4.0.9-alpine
    ports:
      - "6379:6379"

  nsqlookupd:
    image: nsqio/nsq:v0.3.8
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"

  nsqd:
    image: nsqio/nsq:v0.3.8
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 --broadcast-address=127.0.0.1
    links:
      - nsqlookupd:nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"

  nsqadmin:
    image: nsqio/nsq:v0.3.8
    ports:
      - "4171:4171"
    links:
      - nsqlookupd:nsqlookupd
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161

  driver-location:
    build: "driver-location/"
    depends_on:
      - nsqlookupd
      - nsqd
      - redis
    environment:
      SERVER_ADDR: ":8080"
      NSQ_ADDR: "nsqd:4150"
      NSQ_TOPIC: "driver_locations"
      NSQ_CHANNEL: "ch"
      REDIS: "redis:6379"
    ports:
      - "8080:8080"

  zombie-driver:
    build: "zombie-driver/"
    depends_on:
      - driver-location
    environment:
      SERVER_ADDR: ":7070"
      DRIVER_LOCATION_BASE_URL: "driver-location:8080"
    ports:
      - "7070:7070"