// Code generated by protoc-gen-go. DO NOT EDIT.
// source: create_driver_location_message.proto

package pkg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateDriverLocationMessage struct {
	DriverID             string   `protobuf:"bytes,1,opt,name=driverID,proto3" json:"driverID,omitempty"`
	Lat                  float32  `protobuf:"fixed32,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon                  float32  `protobuf:"fixed32,3,opt,name=lon,proto3" json:"lon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDriverLocationMessage) Reset()         { *m = CreateDriverLocationMessage{} }
func (m *CreateDriverLocationMessage) String() string { return proto.CompactTextString(m) }
func (*CreateDriverLocationMessage) ProtoMessage()    {}
func (*CreateDriverLocationMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bb5026956236df0, []int{0}
}

func (m *CreateDriverLocationMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDriverLocationMessage.Unmarshal(m, b)
}
func (m *CreateDriverLocationMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDriverLocationMessage.Marshal(b, m, deterministic)
}
func (m *CreateDriverLocationMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDriverLocationMessage.Merge(m, src)
}
func (m *CreateDriverLocationMessage) XXX_Size() int {
	return xxx_messageInfo_CreateDriverLocationMessage.Size(m)
}
func (m *CreateDriverLocationMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDriverLocationMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDriverLocationMessage proto.InternalMessageInfo

func (m *CreateDriverLocationMessage) GetDriverID() string {
	if m != nil {
		return m.DriverID
	}
	return ""
}

func (m *CreateDriverLocationMessage) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *CreateDriverLocationMessage) GetLon() float32 {
	if m != nil {
		return m.Lon
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateDriverLocationMessage)(nil), "pkg.CreateDriverLocationMessage")
}

func init() {
	proto.RegisterFile("create_driver_location_message.proto", fileDescriptor_7bb5026956236df0)
}

var fileDescriptor_7bb5026956236df0 = []byte{
	// 136 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x49, 0x2e, 0x4a, 0x4d,
	0x2c, 0x49, 0x8d, 0x4f, 0x29, 0xca, 0x2c, 0x4b, 0x2d, 0x8a, 0xcf, 0xc9, 0x4f, 0x4e, 0x2c, 0xc9,
	0xcc, 0xcf, 0x8b, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x62, 0x2e, 0xc8, 0x4e, 0x57, 0x8a, 0xe5, 0x92, 0x76, 0x06, 0x2b, 0x76, 0x01, 0xab, 0xf5,
	0x81, 0x2a, 0xf5, 0x85, 0xa8, 0x14, 0x92, 0xe2, 0xe2, 0x80, 0x18, 0xe2, 0xe9, 0x22, 0xc1, 0xa8,
	0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe7, 0x0b, 0x09, 0x70, 0x31, 0xe7, 0x24, 0x96, 0x48, 0x30, 0x29,
	0x30, 0x6a, 0x30, 0x05, 0x81, 0x98, 0x60, 0x91, 0xfc, 0x3c, 0x09, 0x66, 0xa8, 0x48, 0x7e, 0x9e,
	0x13, 0x6b, 0x14, 0xc8, 0x96, 0x24, 0x36, 0xb0, 0x8d, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x63, 0x5a, 0x24, 0xe6, 0x99, 0x00, 0x00, 0x00,
}
